Authenticated connection for readJsonFileFromBuildArchive
When the remote job is secured and the authentication is configured via global remote jenkins
config the job can be triggered but handle.readJsonFileFromBuildArchive() fails (unauthenticated).

ERROR: ForbiddenException: Server returned 403 - Forbidden.
User does not have enough permissions for this request: http://localhost:8081/jenkins/job/Job1/370/artifact/build-results.json